version: 0.0
os: linux
files:
  - source: /
    destination: /
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 3000
      runas: root
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 300
      runas: root
